version: '3.4'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:-quay.io/api-platform/nginx}
      - ${PHP_IMAGE:-quay.io/api-platform/php}

services:
  php:
    build:
      context: ./api
      target: api_platform_php
      <<: *api-cache-from
    image: ${PHP_IMAGE:-quay.io/api-platform/php}
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw

  api:
    build:
      context: ./api
      target: api_platform_nginx
      <<: *api-cache-from
    image: ${NGINX_IMAGE:-quay.io/api-platform/nginx}
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - target: 80
        published: 8080
        protocol: tcp

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=gametactic
      - MYSQL_DATABASE=gt_users
      - MYSQL_USER=gt_users
      - MYSQL_PASSWORD=please-change-me-asap
    volumes:
      - ./api/docker/db/data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=gt_users
      - PMA_PASSWORD=please-change-me-asap
    ports:
      - target: 80
        published: 80
        protocol: tcp

  h2-proxy:
    # do not use in production!
    build:
      context: ./h2-proxy
    depends_on:
      - api
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 444
        published: 444
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 1338
        published: 1338
        protocol: tcp

volumes:
  db-data: {}
